language: ruby
cache: bundler

rvm:
- "2.3"
- "2.4"
- "2.5"
- "2.6"
- "2.7"

before_script:
- bundle exec run server start --daemon

before_install:
- gem install bundler

script:
- bundle exec rspec
